---
- name: Git | Copy global gitconfig
  copy: src=gitconfig dest=~/.gitconfig mode=0644

- name: Git | Copy global gitignore
  copy: src=gitignore dest=~/.gitignore mode=0644

- name: Oh-My-Zsh | Create Git Dump directory 
  file: path=~/git-dump state=directory mode=0755
